#!/usr/bin/env bash
# A script that displays information about the subdomains.
# shellcheck disable=SC2086

domain_information() {
    RECORD_TYPE=$(dig "$2"."$1" | awk 'BEGIN{OFS=" ";} /^'$2'/{print $4}')
    DESTINATION= $(dig "$2"."$1" | awk 'BEGIN{OFS=" ";} /^'$2'/{print $5}')
    echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi
