#!/usr/bin/ env bash
# Transfers a file from ALX client to a server
# Accept four arguments stated below:
#+	The path to the file to be transferred.
#+	The IP of the server to transfer the file to.
#+	The username that scp connects with.
#+	The path to the SSH private key that scp uses.

# assigning parameters to variables
# path_to_file=$1
# ip=$2
# username=$3
#path_to_ssh_key=$4


if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -lt 4]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi

# checking for successful file transfer
if [ $7 -eq 0 ]; then 
	echo "File Transfer Successful"
else
	echo "File Transfer Failed"
