#!/usr/bin/env bash
# Install nginx server on ubuntu web-01 server
# Nginx should be listening on port 80
# Return a page that contains "Hello World" when querying
# Nginx at its root with Get request using curl
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

echo -e "Updating and Installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y
sudo apt-get install ufw -y
echo -e "\nMaking some minor settings update.\n"

# starting nginx service
sudo service nginx start

# allowing nginx over firewall
ufw allow 'Nginx HTTP'
# Assign ownership of website files to the user for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Creating redirect_me index
echo -e "https://www.jw.org/en/library/videos/intros-for-the-ministry/jehovahs-witnesses-who-are-we-intro" > /var/www/html/redirect_me.html

# Setting up /redirect_me to jw.org page video
use_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.jw.org\/en\/library\/videos\/intros-for-the-ministry\/jehovahs-witnesses-who-are-we-intro permanent;"
sudo sed -i "s/server_name _;/$use_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
