#!/usr/bin/env bash
# Install nginx server on ubuntu web-01 server
# Nginx should be listening on port 80
# Return a page that contains "Hello World" when querying
# Nginx at its root with Get request using curl
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
# Configure your Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page
# The page must return an HTTP 404 error code
#The page must contain the string Ceci n'est pas une page

echo -e "Updating and Installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nMaking some minor settings update.\n"

# starting nginx service
sudo service nginx start

# allowing nginx over firewall
ufw allow 'Nginx HTTP'

# Assign ownership of website files to the user for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a jw.org  page
sudo sed -i '24i\	rewrite ^/redirect_me https://www.jw.org/en/bible-teachings/science/ permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-availabe/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
