#!/usr/bin/env bash
# Install nginx server on ubuntu web-01 server
# Nginx should be listening on port 80
# Return a page that contains "Hello World" when querying
# Nginx at its root with Get request using curl
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
# Configure your Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page

echo -e "Updating and Installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y
sudo apt-get install ufw -y
echo -e "\nMaking some minor settings update.\n"

# starting nginx service
sudo service nginx start

# allowing nginx over firewall
sudo ufw allow 'Nginx HTTP'
# Assign ownership of website files to the user for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Creating redirect_me index
echo -e "https://www.jw.org/en/library/videos/intros-for-the-ministry/jehovahs-witnesses-who-are-we-intro" > /var/www/html/redirect_me.html

# Creating the error message for errror_404
echo -e "Ceci n'est pas une page" > /var/www/html/error_404.html

# Setting up redirect_me to a jw.org page
use_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.jw.org\/en\/library\/videos\/intros-for-the-ministry\/jehovahs-witnesses-who-are-we-intro permanent;"
sudo sed -i "s/server_name _;/$use_for_replacement/" /etc/nginx/sites-enabled/default

# Set up a 404 page
string_for_error="listen 80 default_server;\n\terror_page 404 \/error_404.html;\n\tlocation = \/error_404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_error/" /etc/nginx/sites-enabled/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
