#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAproxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure HAproxy can be can be managed via an init script
# Make sure your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

# Installing and configure HAproxy Load balancer on my lb-01 server

echo -e "Updating and doing server configuration checks...\n"


sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Install haproxy
sudo apt-get install haproxy

echo -e "\nSetting up configurations for HAproxy.\n"

# Backup default server configuration settings on HAproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.bckup}

# Edit configuration file
server_config=\
"
frontend balsam
	bind *:80
	mode http
	default_backend gilead
backend gilead
	balance roundrobin
	server 520156-web-01 34.227.94.180:80 check
	server 520156-web-02 100.25.167.156:80 check
"

# Shellcheck disable=SC2154
echo "$server_config" >> /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

# Test the configuration for HAproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
