#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it

#variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
filename="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root -password="$1" >> backup.sql
tar -czvf "$filename" backup.sql
