#!/usr/bin/env bash
# Bash script that uses ssh to connect to my local server using the private
# key ~/.ssh/school with the user ubuntu
# using eval agent to login into the web server

eval $("ssh-agent")
ssh-add ~/.ssh/school
ssh ubuntu@52.91.117.56
