#!/usr/bin/env bash
# Bash script that uses ssh to connect to my local server using the private
# key ~/.ssh/school with the user ubuntu

ssh ubuntu@34.227.94.180 -i ~/.ssh/school

# using eval agent to login into the web server
# eval $("ssh-agent")
# ssh-add ~/.ssh/school
# ssh ubuntu@34.227.94.180
